version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - 15432:5432
    volumes:
      - ~/labs/adopet-backend/data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "umemail@example.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
